# 我这个docker compose 由几个服务组成
version: "3"
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root 
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13316:3306"


  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
      -
  etcd:
    image: "bitnami/etcd:latest"
    restart: always
    entrypoint:
      - ALLOW_NON_AUTHENTICATION=yes
    ports:
      - "12379:2379"